### ISSUE TITLE
사용자 회원가입 및 로그인 기능을 구현한다

### ISSUE THREAD

**Issue by boroboro01** [2024-Saphy/App#19]
# Description
소셜 로그인 두 종을 구현합니다. (구글, 카카오)
회원가입 기능을 구현합니다.
자동 로그인 기능을 구현합니다.
# Changes
- [x] 구글 로그인 기능을 추가한다.
- [x] 카카오 로그인 기능을 추가한다.
- [x] 회원가입 기능을 추가한다.
- [x] 전화번호 OTP 인증 기능을 추가한다.
- [x] 자동 로그인 기능을 추가한다.
# Additional context

**Comment by devlwh0830** [comment]
이거 이제 닫아도 되지 않나요?

**Comment by boroboro01** [comment]
> 이거 이제 닫아도 되지 않나요?

👍🏻
