### ISSUE TITLE
🖌️ Splash Screen을 개선한다

### ISSUE THREAD

**Issue by boroboro01** [2024-Saphy/App#20]
# Description
Splash Screen을 더 예쁘게 만듭니다

# Changes
- [x] Splash Screen Design 논의
- [x] Splash Screen 개선

# Additional context

**Comment by devlwh0830** [comment]
애니메이션 넣기..?

**Comment by boroboro01** [comment]
> 애니메이션 넣기..?

배경 메인 컬러로 하고 중앙에 로고 띄우기가 디폴트인데
좀 이쁘게 하려면 애니메이션 넣는게 좋을듯...?

**Comment by yummjin** [comment]
댓글도 달 수 있었구나
이번에 Figma에서 수정한 거
배경 색 바꾸고 로고 크게 키운 건데
로고가 가로로 움직이는 애니메이션 넣어도 좋을듯..

**Comment by boroboro01** [comment]
> 댓글도 달 수 있었구나 이번에 Figma에서 수정한 거 배경 색 바꾸고 로고 크게 키운 건데 로고가 가로로 움직이는 애니메이션 넣어도 좋을듯..

나도 딱 그거 생각했는데
구현해보겠슴다

**Comment by boroboro01** [comment]
새로운 디자인이 생겼으니 이 이슈는 닫습니다
