### ISSUE TITLE
일부 디바이스 UI 오버플로우 에러

### ISSUE THREAD

**Issue by devlwh0830** [2024-Saphy/App#29]
# Description
화면 깨짐 현상이 일부 디바이스에서 발견되고 있습니다.
확인 기종 : Samsung S24+

![Screenshot_20240831_172902](https://github.com/user-attachments/assets/3497a5ee-4e2c-46cb-862c-4a498b3dfed6)
![Screenshot_20240831_172906](https://github.com/user-attachments/assets/ddafd62d-4339-40fe-9a99-4885ea3d8d5e)
![Screenshot_20240831_172909](https://github.com/user-attachments/assets/dc00e5f8-233b-419c-99fd-2c485c2c150d)

# Changes
- [x] 검색창 오버플로우 해결
- [x] 메인, 찜목록 상품 표시 일렬 현상 해결

# Additional context

**Comment by yummjin** [comment]
아 이거 저도 확인했는데 상품 카드 사이즈를 정해놓고 하다보니 그런 것 같아요
상품 카드 가로 사이즈를 어떻게 정해줘야 할지 모르겠음.
Wrap 위젯에 가로 꽉 채우는 기능 있는지 확인해볼 예정

**Comment by yummjin** [comment]
Wrap의 경우 한 행에 요소를 몇 개 넣을지 정해줄 수 없기 때문에
현재로서는 상품 카드의 가로 너비를 요소 별로 다르게 하는 방법이 가장 최선인듯 함
다른 좋은 방법 있는 것 같으면 건의 부탁드립니다.
https://api.flutter.dev/flutter/widgets/Wrap-class.html

**Comment by devlwh0830** [comment]
흠 저도 한 번 해결 해볼게요

**Comment by boroboro01** [comment]
카드 가로 너비를 MediaQuery와 ratio를 통해서 동적으로 설정 가능합니다

**Comment by yummjin** [comment]
> 카드 가로 너비를 MediaQuery와 ratio를 통해서 동적으로 설정 가능합니다

확인.. 찾아보고 수정할게요

**Comment by yummjin** [comment]
수정했습니다 머지후 확인부탁드립니다
