### ISSUE TITLE
일부 디바이스 UI 오버플로우 에러 2

### ISSUE THREAD

**Issue by devlwh0830** [2024-Saphy/App#39]
# Description
화면 깨짐 현상이 일부 디바이스에서 발견되고 있습니다.
확인 기종 : iPhone 15 Pro

<img width="380" alt="image" src="https://github.com/user-attachments/assets/a8f94e0c-ed49-41a2-93f4-be4b45cce98a">
<img width="401" alt="imag2e" src="https://github.com/user-attachments/assets/49556516-9e31-46ed-b94d-002dcbb4b855">

# Changes
- [x] BottomeNavigationBar 오버플로우 해결
- [x] 상품 상세 페이지 등급 배너 오버플로우 해결  

# Additional context

**Comment by yummjin** [comment]
아니.. navBar는 왜 오버플로우가 나지..
이거 메인페이지 캐러셀 추가하면서 이번주안으로 해결해오겠습니다

**Comment by devlwh0830** [comment]
오 좋습니다 👏

**Comment by yummjin** [comment]
에러 해결 했씁니다!! 확인 부탁 드리고 확인되면 닫아주세여

**Comment by devlwh0830** [comment]
똑같은 기종에서 BottomNavBar 오버플로우 에러 해결이 안돼서 일단 제가 확인해보고 나중에 합칠게요 🧐
상세페이지 쪽은 해결된거 확인했습니당

**Comment by yummjin** [comment]
아 지금 보니까 아이콘이 넘치는 거였네요
후딱 수정해서 올리겠습니다

**Comment by yummjin** [comment]
수정했습니다~!
